version: '3.7'
services:
  worker:
    build:
      context: .
      target: bht-test
      args:
        - USER_UID=1000
        - USER_GID=1000
    command: python manage.py run_worker
    volumes:
      - ./DATA:/home/bibheliotech/BibHelioTech/DATA:rw
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    depends_on:
      grobid:
        condition: service_healthy

  grobid:
    image: lfoppiano/grobid:0.7.2
    ports:
      - "8070:8070"
    healthcheck:
      test: [
        "CMD", "bash", "-c",
        "while ! timeout 1 bash -c 'echo > /dev/tcp/localhost/8070'; do sleep 10; done"
      ]
