FROM lfoppiano/grobid:0.7.2

RUN apt-get update && \
    apt-get install  -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

HEALTHCHECK  --interval=5s --timeout=5s --retries=5 CMD curl --fail http://localhost:8070/api/isalive || exit 1
