"""empty message

Revision ID: 144260ce462b
Revises: f8b664f24f81
Create Date: 2024-09-06 06:27:27.513357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144260ce462b'
down_revision = 'f8b664f24f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hp_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conf', sa.Float(), nullable=True))
        batch_op.drop_column('conf_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hp_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conf_idx', sa.FLOAT(), nullable=True))
        batch_op.drop_column('conf')

    # ### end Alembic commands ###
