"""empty message

Revision ID: ddb85671ad8b
Revises: 144260ce462b
Create Date: 2024-09-06 06:37:42.892671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb85671ad8b'
down_revision = '144260ce462b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hp_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('r', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hp_event', schema=None) as batch_op:
        batch_op.drop_column('r')
        batch_op.drop_column('d')

    # ### end Alembic commands ###
