"""empty message

Revision ID: e3207db7c9b1
Revises: 0eec168a5e17
Create Date: 2024-09-05 14:28:06.623764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3207db7c9b1'
down_revision = '0eec168a5e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hp_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conf_idx', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hp_event', schema=None) as batch_op:
        batch_op.drop_column('conf_idx')

    # ### end Alembic commands ###
