"""empty message

Revision ID: eaab1032819a
Revises:
Create Date: 2023-03-11 08:52:03.004387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eaab1032819a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hp_event", schema=None) as batch_op:
        batch_op.alter_column(
            "start_date",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "stop_date",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hp_event", schema=None) as batch_op:
        batch_op.alter_column(
            "stop_date",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "start_date",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
