import csv
import datetime
import textwrap

from bht_config import yml_settings

hpevent_keys_ordered = [
    "start_time",
    "stop_time",
    "doi",
    "sats",
    "insts",
    "regs",
    "d",
    "r",
    "so",
    "occur_sat",
    "nb_durations",
    "conf",
]

hpevent_parameters = {
    "start_time": {"col_name": "START_TIME", "size": 1, "type": "date"},
    "stop_time": {"col_name": "STOP_TIME", "size": 1, "type": "date"},
    "doi": {"col_name": "DOI", "size": 1, "type": "char"},
    "sats": {"col_name": "SATS", "size": 1, "type": "char"},
    "insts": {"col_name": "INSTS", "size": 1, "type": "char"},
    "regs": {"col_name": "REGS", "size": 1, "type": "char"},
    "d": {"col_name": "D", "size": 1, "type": "int"},
    "r": {"col_name": "R", "size": 1, "type": "int"},
    "so": {"col_name": "SO", "size": 1, "type": "int"},
    "occur_sat": {"col_name": "OCCUR_SAT", "size": 1, "type": "int"},
    "nb_durations": {"col_name": "NB_DURATIONS", "size": 1, "type": "int"},
    "conf": {"col_name": "CONF", "size": 1, "type": "float"},
}


def row_to_dict(event_row):
    """
    From a row of value, transform to a dict with keys.
    The row values may follow the  order of hpevent_keys_ordered list

    @param event_row:  row of hpevent values
    @return:  hpevent_dict
    """
    _r_dict = {}
    num_cols = len(event_row)
    hpevent_keys = hpevent_keys_ordered[0:num_cols]
    hpevent_tuple = zip(hpevent_keys, event_row)
    for k, v in hpevent_tuple:
        _r_dict[k] = v
    return _r_dict


def dict_to_row(event_dict):
    """
    From an event dict, transform to a right ordered row values 'space' separated.

    @param event_dict:  hpevent dictionnary with variable number of keys
    @return:  row of the event's values
    """
    _r_row = []
    hpevent_keys = hpevent_keys_ordered[0 : len(event_dict.keys())]
    for _k in hpevent_keys:
        _r_row.append(event_dict[_k])
    return _r_row


def rows_to_catstring(events_list, catalog_name, columns=None):
    """
    Build a text file of events in amda catalog format

    Events are given as a list of dicts with at least the keys

        ['doi','instrument','mission','region','start_date','stop_date']

    @param events_list: a list of events as dicts
    @param catalog_name:  the name of the catalog being created
    @param columns: the keys of the event dict we want to write down
    @return: a string containing the events' catalog as text
    """

    if columns is None:
        columns = list(hpevent_parameters.keys())

    # Print catalog's general header
    date_now = datetime.datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    r_string = f"""
    # Name: {catalog_name};
    # BibHelioTechVersion: V{yml_settings["BHT_PIPELINE_VERSION"]};
    # Creation Date: {date_now};
    # Description: Catalogue of events resulting from the HelioNER code
    # (Dablanc & Génot, "https://github.com/ADablanc/BibHelioTech.git")
    #
    # Dynamically generated by the BibHelioTech web service.
    #
    # The two first columns are the start/stop times of the event.
    # The third column is the DOI of the paper,
    # The fourth column is the mission that observed the event with the list of instruments listed in the fifth column.
    # The sixth column is the most probable region of space where the observation took place (SPASE ObservedRegions term);
    #
    """
    r_string = textwrap.dedent(r_string)

    # Print parameters header
    p_index = 0
    for k, v in hpevent_parameters.items():
        if k not in columns:
            continue
        r_string += f'# Parameter {p_index}: id:column{p_index}; name: {v["col_name"]}; size:{v["size"]}; type:{v["type"]};\n'
        p_index += 1
    for e in events_list:
        r_string += f"{e['start_time']} {e['stop_time']} {e['doi']} {e['sats']} {e['insts']} {e['regs']}\n"
    return r_string


def catfile_to_rows(catfile):
    """Get all rows of a catalog file as  dict
       -  read each line, rid of comments
       -  create a hp_event_dict

       Trick: we may get catfiles with different number of columns.
           sometimes  6 (start, stop, doi, mission, instruments, region)
           sometimes 12 ( ..., D, R, SO, occur_sat, nb_durations, conf)

       This is the reason of row_to_dict use.

    :return: hpevent_dict list
    """
    hpeventdict_list = []
    with open(catfile, newline="") as csvfile:
        reader = csv.reader(
            filter(lambda r: r[0] != "#", csvfile), delimiter=" ", quotechar='"'
        )
        for row in reader:
            hpevent_dict = row_to_dict(row)
            hpeventdict_list.append(hpevent_dict)
    return hpeventdict_list
