import csv
import datetime
import textwrap

from bht_config import yml_settings


def rows_to_catstring(events_list, catalog_name, columns=None):
    """
    Build a text file of events in amda catalog format

    Events are given as a list of dicts with at least the keys

        ['doi','instrument','mission','region','start_date','stop_date']

    @param events_list: a list of events as dicts
    @param catalog_name:  the name of the catalog being created
    @param columns: the keys of the event dict we want to write down
    @return: a string containing the events' catalog as text
    """

    parameters = {
        "start_date": {"name": "START_DATE", "size": 1, "type": "date"},
        "stop_date": {"name": "STOP_DATE", "size": 1, "type": "date"},
        "doi": {"name": "DOI", "size": 1, "type": "char"},
        "sats": {"name": "SATS", "size": 1, "type": "char"},
        "insts": {"name": "INSTS", "size": 1, "type": "char"},
        "regs": {"name": "REGS", "size": 1, "type": "char"},
        "d": {"name": "D", "size": 1, "type": "int"},
        "r": {"name": "R", "size": 1, "type": "int"},
        "so": {"name": "SO", "size": 1, "type": "int"},
        "occur_sat": {"OCCUR_SAT": "START_DATE", "size": 1, "type": "int"},
        "nb_durations": {"NB_DURATIONS": "START_DATE", "size": 1, "type": "int"},
        "conf": {"name": "CONF", "size": 1, "type": "float"},
    }
    if columns is None:
        columns = list(parameters.keys())

    # Print catalog's general header
    date_now = datetime.datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    r_string = f"""
    # Name: {catalog_name};
    # BibHelioTechVersion: V{yml_settings["BHT_PIPELINE_VERSION"]};
    # Creation Date: {date_now};
    # Description: Catalogue of events resulting from the HelioNER code
    # (Dablanc & Génot, "https://github.com/ADablanc/BibHelioTech.git")
    #
    # Dynamically generated by the BibHelioTech web service.
    #
    # The two first columns are the start/stop times of the event.
    # The third column is the DOI of the paper,
    # The fourth column is the mission that observed the event with the list of instruments listed in the fifth column.
    # The sixth column is the most probable region of space where the observation took place (SPASE ObservedRegions term);
    #
    """
    r_string = textwrap.dedent(r_string)

    # Print parameters header
    p_index = 0
    for k, v in parameters.items():
        if k not in columns:
            continue
        r_string += f'Parameter {p_index}: id:column{p_index}; name: {v["name"]}; size:{v["size"]}; type:{v["type"]};\n'
        p_index += 1
    for e in events_list:
        r_string += f"{e['start_date']} {e['stop_date']} {e['doi']} {e['mission']} {e['instrument']} {e['region']}\n"
    return r_string


def catfile_to_rows(catfile):
    """Get all rows of a catalog file as  dict

      TODO: MODEL should move to Paper or Catalog method

       -  read each line, rid of comments
       -  create a hp_event_dict
    :return: hpevent_dict list
    """
    hpeventdict_list = []
    with open(catfile, newline="") as csvfile:
        reader = csv.reader(
            filter(lambda r: r[0] != "#", csvfile), delimiter=" ", quotechar='"'
        )
        for row in reader:
            hpevent_dict = {
                "start_date": row[0],
                "stop_date": row[1],
                "doi": row[2],
                "mission": row[3],
                "instrument": row[4],
                "region": row[5],
            }

            hpeventdict_list.append(hpevent_dict)
    return hpeventdict_list
