name: ovh-build-deploy

on:
  push:
    branches:
      - "dev-deploy"

jobs:

  deploy-to-ovh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run from OVH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWD }}
          port: 22
          script: |
            cd bht-dev
            WEB_TAG=dev WEB_PORT=8081 docker compose -p bht-dev down
            git checkout  dev-deploy
            git reset --hard  dev-deploy
            git pull
            WEB_TAG=dev WEB_PORT=8081 docker compose -p bht-dev up -d   --build
