name: unittest-ci

on:
  push:
    branches:
      - "test"
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-tests.txt ]; then pip install -r requirements-tests.txt; fi
      - name: Lint with flake8
        run: |
          cp resources/flake8-dist .flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build Docker stack
        run: |
          docker compose -f docker-compose.tests.yml up -d --build
          docker compose logs grobid
          docker compose logs redis
          docker ps -a
      - name: Set hostnames
        run: |
          sudo echo "127.0.0.1 grobid" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 redis" | sudo tee -a /etc/hosts
      - name: Test with pytest
        run: |
          cp resources/grobid-client-config.json-dist grobid-client-config.json
          cp resources/bht-config.yml-dist bht-config.yml
          cp resources/pytest.ini-dist pytest.ini
          python manage.py create_db
          pytest
